[package]
name = "kafka-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.22", features = ["std"] }
rdkafka = { version = "0.37.0", features = ["cmake-build"]}
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
